server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  #mysql驱动包
    url: jdbc:mysql://39.96.178.201:3306/cloud2020?useUnicode=true?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml  #mapper.xml文件所在地址
  type-aliases-package: com.cmlx.entities #所以Entity别名类所在包
